/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized.glb -T 
Files: optimized.glb [7.78MB] > C:\Users\saids\WebstormProjects\habitable_worlds\public\models\optimized-transformed.glb [6.62MB] (15%)
Author: dannzjs (https://sketchfab.com/dannzjs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/futuristic-spaceship-89b1b3f200c84d5a990ae95c0e302848
Title: Futuristic Spaceship
*/

import { useGLTF } from '@react-three/drei'

export default function SpaceShip(props) {
  const { nodes, materials } = useGLTF('/models/optimized-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Preview} position={[0, -0.001, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={3.2} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.container1} position={[0, 0.685, -1.152]} rotation={[-Math.PI / 2, 0, 0]} scale={2.968} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.engflames1} position={[0, 1.72, -6.991]} rotation={[-Math.PI / 2, 0, 0]} scale={2.523} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.engines11} position={[0, 1.887, -3.481]} rotation={[-Math.PI / 2, 0, 0]} scale={3.096} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.engines21} position={[0, 1.79, -5.955]} rotation={[-Math.PI / 2, 0, 0]} scale={3.343} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.glasshard1} position={[0, 1.904, 2.046]} rotation={[-Math.PI / 2, 0, 0]} scale={4.21} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.glassoft1} position={[0, 1.444, 0.484]} rotation={[-Math.PI / 2, 0, 0]} scale={5.855} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.inerwallpanels1} position={[0, 2.188, -3.25]} rotation={[-Math.PI / 2, 0, 0]} scale={1.595} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.ladders2} position={[0, 0.962, 1.762]} rotation={[-Math.PI / 2, 0, 0]} scale={3.046} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.lights1} position={[0, 1.532, -1.172]} rotation={[-Math.PI / 2, 0, 0]} scale={6.52} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.maindesk4panel1} position={[0, 1.835, -2.309]} rotation={[-Math.PI / 2, 0, 0]} scale={1.321} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.mainfloor1} position={[0, 1.235, -2.351]} rotation={[-Math.PI / 2, 0, 0]} scale={3.631} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.mainner11} position={[0, 2.052, -1.621]} rotation={[-Math.PI / 2, 0, 0]} scale={2.841} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.mainner21} position={[0, 1.678, -2.576]} rotation={[-Math.PI / 2, 0, 0]} scale={3.863} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.mainner31} position={[0, 1.994, 0.754]} rotation={[-Math.PI / 2, 0, 0]} scale={1.916} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.mainout11} position={[0, 1.902, -1.666]} rotation={[-Math.PI / 2, 0, 0]} scale={3.29} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.mainout21} position={[0, 0.959, -1.611]} rotation={[-Math.PI / 2, 0, 0]} scale={3.412} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.mainpanel11} position={[0, 2, -1.814]} rotation={[-Math.PI / 2, 0, 0]} scale={1.076} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.mainpanel2L1} position={[0.989, 1.895, -0.431]} rotation={[-Math.PI / 2, 0, 0]} scale={1.105} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.mainpanel2R1} position={[-1.029, 2.081, -0.206]} rotation={[-Math.PI / 2, 0, 0]} scale={1.329} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.mainpanel31} position={[0, 2.136, -1.089]} rotation={[-Math.PI / 2, 0, 0]} scale={2.372} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.mainpanelextra1} position={[0, 2.088, -1.667]} rotation={[-Math.PI / 2, 0, 0]} scale={1.273} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.module11} position={[0, 1.973, -1.829]} rotation={[-Math.PI / 2, 0, 0]} scale={1.735} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.module21} position={[0.226, 1.823, -0.397]} rotation={[-Math.PI / 2, 0, 0]} scale={1.508} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.module31} position={[0, 1.805, -2.021]} rotation={[-Math.PI / 2, 0, 0]} scale={1.918} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.noseaccessories1} position={[0, 1.279, 3.422]} rotation={[-Math.PI / 2, 0, 0]} scale={2.583} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.nosefloor1} position={[0, 1.354, 3.676]} rotation={[-Math.PI / 2, 0, 0]} scale={2.405} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.noseinner11} position={[0, 1.736, 4.574]} rotation={[-Math.PI / 2, 0, 0]} scale={1.822} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.noseinner21} position={[0, 1.412, 3.805]} rotation={[-Math.PI / 2, 0, 0]} scale={2.534} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.noseinner31} position={[0, 1.607, 3.347]} rotation={[-Math.PI / 2, 0, 0]} scale={2.156} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.noseout11} position={[0, 1.549, 4.866]} rotation={[-Math.PI / 2, 0, 0]} scale={2.232} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.noseout21} position={[0, 1.352, 4.304]} rotation={[-Math.PI / 2, 0, 0]} scale={3.02} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.nosepanel11} position={[0, 1.402, 4.983]} rotation={[-Math.PI / 2, 0, 0]} scale={0.907} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.nosepanel21} position={[0, 1.645, 3.741]} rotation={[-Math.PI / 2, 0, 0]} scale={1.496} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.nosepanel31} position={[0, 1.886, 3.117]} rotation={[-Math.PI / 2, 0, 0]} scale={1.503} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.nosepanel41} position={[0, 1.839, 2.702]} rotation={[-Math.PI / 2, 0, 0]} scale={1.531} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.nosepanel51} position={[0, 1.465, 4.11]} rotation={[-Math.PI / 2, 0, 0]} scale={1.457} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.reargate1} position={[0, 0.744, -7.131]} rotation={[-Math.PI / 2, 0, 0]} scale={1.092} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.rearout11} position={[0, 1.552, -5.51]} rotation={[-Math.PI / 2, 0, 0]} scale={3.29} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.rearout21} position={[0, 1.447, -5.233]} rotation={[-Math.PI / 2, 0, 0]} scale={3.29} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.rearpanels1} position={[0, 1.808, -5.207]} rotation={[-Math.PI / 2, 0, 0]} scale={1.38} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.seathard1} position={[0, 1.632, 0.901]} rotation={[-Math.PI / 2, 0, 0]} scale={4.42} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.seatsoft1} position={[0.22, 1.722, 0.882]} rotation={[-Math.PI / 2, 0, 0]} scale={4.361} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.subgate1} position={[0, 0.639, -7.176]} rotation={[-Math.PI / 2, 0, 0]} scale={0.65} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.turretgun1} position={[0, 2.651, -2.607]} rotation={[-Math.PI / 2, 0, 0]} scale={0.793} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.wingsrearacc1} position={[0, 1.758, -4.475]} rotation={[-Math.PI / 2, 0, 0]} scale={5.624} />
    </group>
  )
}

useGLTF.preload('/models/optimized-transformed.glb')
